import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export interface ResolvedAddresses {
  manager: string;
  bookingToken: string;
  cmAccountImpl: string;
}

const CANONICAL = "CaminoMessengerModule";

export function resolveAddresses(
  deployments: Record<number, Record<string, string>>,
): Record<number, ResolvedAddresses> {
  const result: Record<number, ResolvedAddresses> = {};
  for (const [chainIdStr, keys] of Object.entries(deployments)) {
    const chainId = Number(chainIdStr);
    const manager = keys[`${CANONICAL}#ManagerProxy`];
    const bookingToken = keys[`${CANONICAL}#BookingTokenProxy`];
    const cmAccountImpl = keys[`${CANONICAL}#CMAccount`];
    if (!manager || !bookingToken || !cmAccountImpl) continue;
    result[chainId] = { manager, bookingToken, cmAccountImpl };
  }
  return result;
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..");
const DEPLOY_DIR = join(REPO_ROOT, "ignition", "deployments");
const ABI_DIR = join(REPO_ROOT, "abi", "contracts");
const OUT_DIR = join(__dirname, "..", "src", "contracts", "generated");
const CHAIN_IDS = [500, 501, 8453, 84532];

function loadDeployments(): Record<number, Record<string, string>> {
  const out: Record<number, Record<string, string>> = {};
  for (const id of CHAIN_IDS) {
    const file = join(DEPLOY_DIR, `chain-${id}`, "deployed_addresses.json");
    if (existsSync(file)) out[id] = JSON.parse(readFileSync(file, "utf8"));
  }
  return out;
}

function loadAbi(relPath: string): unknown {
  return JSON.parse(readFileSync(join(ABI_DIR, relPath), "utf8"));
}

function main(): void {
  const resolved = resolveAddresses(loadDeployments());
  mkdirSync(OUT_DIR, { recursive: true });

  writeFileSync(
    join(OUT_DIR, "addresses.ts"),
    `// AUTO-GENERATED by scripts/sync-contracts.ts. Do not edit.
export interface ResolvedAddresses { manager: string; bookingToken: string; cmAccountImpl: string; }
export const ADDRESSES: Record<number, ResolvedAddresses> = ${JSON.stringify(resolved, null, 2)};
`,
  );

  const manager = loadAbi("manager/CMAccountManager.sol/CMAccountManager.json");
  const cmAccount = loadAbi("account/CMAccount.sol/CMAccount.json");
  const bookingToken = loadAbi("booking-token/BookingToken.sol/BookingToken.json");

  writeFileSync(
    join(OUT_DIR, "abis.ts"),
    `// AUTO-GENERATED by scripts/sync-contracts.ts. Do not edit.
export const MANAGER_ABI = ${JSON.stringify(manager)} as const;
export const CMACCOUNT_ABI = ${JSON.stringify(cmAccount)} as const;
export const BOOKINGTOKEN_ABI = ${JSON.stringify(bookingToken)} as const;
`,
  );

  console.log(`Synced ${Object.keys(resolved).length} chains to ${OUT_DIR}`);
}

// Run main only when executed directly (not when imported by tests).
if (process.argv[1] && process.argv[1].endsWith("sync-contracts.ts")) {
  main();
}
